services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hydianflow
      POSTGRES_PASSWORD: hydianflow
      POSTGRES_DB: hydianflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hydianflow -d hydianflow"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    # Call the migrate binary directly (exec form) and include 'up' here:
    entrypoint: ["/migrate"]
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://hydianflow:hydianflow@db:5432/hydianflow?sslmode=disable",
        "up"
      ]

  api:
    image: ghcr.io/ajmerr/hydianflow-api:latest
    environment:
      DATABASE_URL: postgres://hydianflow:hydianflow@db:5432/hydianflow?sslmode=disable
      DEV_AUTH: "0"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
